# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  rules:
    constant_identifier_names: false
    unnecessary_overrides: false # This one mostly comes from json_serializable package generated files, which is quite annoying